// <auto-generated />
using System;
using APISCH;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APISCH.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20211015042953_companyadd")]
    partial class companyadd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APISCH.Entities.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyTitle = "Golrang"
                        });
                });

            modelBuilder.Entity("APISCH.Entities.ImportExport", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ImportExportType")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("ID");

                    b.ToTable("ImportExports");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            ImportExportType = true,
                            IsActive = true,
                            RegisterTime = new DateTime(2021, 10, 15, 7, 59, 52, 917, DateTimeKind.Local).AddTicks(8596),
                            TagID = "110A02EF1250"
                        });
                });

            modelBuilder.Entity("APISCH.Entities.Person", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint");

                    b.Property<int>("CompanyID_FK")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("RegisterTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID_FK");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            ID = "c6dee22d-6ac3-4355-a5d4-c530c319ed31",
                            Age = (byte)35,
                            CompanyID_FK = 1,
                            FName = "Farshid",
                            IsActive = true,
                            LName = "Mohammadi",
                            PhoneNumber = "9186620474",
                            RegisterTime = new DateTime(2021, 10, 15, 7, 59, 52, 920, DateTimeKind.Local).AddTicks(1736)
                        });
                });

            modelBuilder.Entity("APISCH.Entities.Person", b =>
                {
                    b.HasOne("APISCH.Entities.Company", "Company")
                        .WithMany("People")
                        .HasForeignKey("CompanyID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("APISCH.Entities.Company", b =>
                {
                    b.Navigation("People");
                });
#pragma warning restore 612, 618
        }
    }
}
